import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { AuthModalAppContextProvider } from "@/shared/context/appContext";
import { StoreProvider } from "@/shared/providers/store-provider";
import { ReactNode } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer theme="colored" hideProgressBar autoClose={3000} />
        <StoreProvider>
          <AuthModalAppContextProvider>{children}</AuthModalAppContextProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
