/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * e-commerce
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import { createInstance } from "./api-instance";
import type { BodyType } from "./api-instance";
/**
 * Информация о пользователе
 */
export type LoginResponseTypeUser = { [key: string]: any };

export interface LoginResponseType {
  /** Сообщение о результате входа */
  message: string;
  /** Информация о пользователе */
  user: LoginResponseTypeUser;
}

export interface LoginUserDto {
  /** Адрес электронной почты пользователя */
  email: string;
  /**
   * Пароль пользователя
   * @minimum 5
   */
  password: string;
}

export interface ActivateResponseType {
  /** Сообщение об успешной активации */
  message: string;
}

export interface ActivateUserDto {
  /**
   * Код активации (четыре цифры)
   * @minimum 4
   * @maximum 4
   */
  code: string;
  /** Email пользователя */
  email: string;
}

export interface RegistrationResponseType {
  /** Сообщение о результате регистрации */
  message: string;
}

export interface CreateUserDto {
  /** Адрес электронной почты пользователя */
  email: string;
  /** Пароль пользователя */
  password: string;
  /** Имя пользователя */
  username: string;
}

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const register = (
  createUserDto: BodyType<CreateUserDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<RegistrationResponseType>(
    {
      url: `/users/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createUserDto,
    },
    options,
  );
};

export const activate = (
  activateUserDto: BodyType<ActivateUserDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<ActivateResponseType>(
    {
      url: `/users/activate`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: activateUserDto,
    },
    options,
  );
};

export const login = (
  loginUserDto: BodyType<LoginUserDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<LoginResponseType>(
    {
      url: `/users/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginUserDto,
    },
    options,
  );
};

export const refreshToken = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    { url: `/users/refresh-token`, method: "GET" },
    options,
  );
};

export type RegisterResult = NonNullable<Awaited<ReturnType<typeof register>>>;
export type ActivateResult = NonNullable<Awaited<ReturnType<typeof activate>>>;
export type LoginResult = NonNullable<Awaited<ReturnType<typeof login>>>;
export type RefreshTokenResult = NonNullable<
  Awaited<ReturnType<typeof refreshToken>>
>;
